### ISSUE TITLE
Doubt on Standard Error

### ISSUE THREAD

**Issue by piever** [kkholst/EventHistory.jl#2]
Hi! Following [this discussion](https://discourse.julialang.org/t/survival-analysis-in-julia/969/6) I've decided to try and build a comprehensive package for survival analysis. I've started implementing Cox regression using a method which seems to be very similar to yours (computing negative log-likelihood, gradient and hessian and applying Newton-Raphson algorithm with backtracking) with Efron method for ties. I have a doubt on the computation of S.E. of the parameters: what I'd do is to use the Hessian of the parameter vector beta in the point of maximum likelihood to build a multivariate gaussian approximation and then use that gaussian approximation to get the S.E. In your code however this seems to be "Naive S.E" and you compute the actual "S.E." in a different way that I'm not sure I understand. Could you elucidate me on that?

Thanks in advance!

**Comment by kkholst** [comment]
The S.E. I report are the sandwich estimates. Both agrees if the model is correctly specified. 
Nice with some additional effort being put in to implementing survival analysis methods - perhaps some form of collaboration would make sense?

**Comment by piever** [comment]
Sure! Also somebody on the julialang forum expressed interest so I guess we can start a small collaboration. For the time being I think what's going on is the following:

- I have a Cox regression implementation that I've tried to optimize to a good extent and is at the moment faster than EventHistory, so I'd keep it as it is and maybe try to optimize a bit further in the future (at a first superficial benchmark, it seems as fast as the matlab implementation - at least the Efron method, I haven't implemented anything else)
- I think your types to represent events and their visualizations are much nicer than what I have, can I incorporate that? It'd be nice for consistency
- In terms of future plans, my priority is to have: Nelson Aalen method for cumulative hazard, some smoothing to get the hazard, Kaplan Meier method for cdf (which is implemented already but may need a bit of cleaning), accelerated failure time model (where I imagine the user could either give a parametrized distribution or use some prebuilt example, e.g. Gamma or Weibull)
- I see in your roadmap that you have planned additive models (a very valuable addition which I was not planning to add due to lack of time) + other things that I'm not familiar with at the moment (definitely my bad, I'll be reading about those).

One reasonable way to proceed would be for me to carry on with my plan (possibly using the same types as you do, for compatibility and better visualization) while you could continue with your roadmap (which except Efron method that I've implemented is non-overlapping with what I have). In the not so far future I think we can merge the two packages.

**Comment by kkholst** [comment]
Sounds great. Looking forward to discuss this further (please find my contact information from the link to my homepage on my github front page).
